[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.2.1" }
wally = { github = "UpliftGames/wally", version = "0.3.1" }
selene = { github = "Kampfkarren/selene", version = "0.20.0" }
stylua = { github = "JohnnyMorganz/stylua", version = "0.14.2" }